---
# This playbook contains common plays that will be run on all nodes.

# ==> SSH sanity check.

# update apt cache
- name: Update apt cache
  become: yes
  become_user: root
  apt:
    update_cache: yes

# make sure that OpenSSH is installed
- name: install OpenSSH
  become: yes
  become_user: root
  apt:
    name:
      - openssh-client
      - openssh-server
      - openssh-sftp-server
    state: present

# ==> ufw

# enable firewall
- name: Allow SSH port
  become: yes
  become_user: root
  ufw:
    rule: allow
    port: ssh
  notify: enable ufw

# ==> dkms

# make sure that dkms is installed
- name: install dkms
  become: yes
  become_user: root
  apt:
    name:
      - dkms
    state: present

# ==> apt - get latest packages

# update cache
- name: Update apt cache
  become: yes
  become_user: root
  apt:
    update_cache: yes

# upgrade
- name: Upgrade installed packages
  become: yes
  become_user: root
  apt:
    upgrade: dist

# Install first set of needed packages
- name: install lots of packages
  become: yes
  become_user: root
  apt:
    name:
      - screen
      - vim
      - git
      - linux-image-generic
      - linux-headers-generic
      - python
      - python3
      - subversion
      - links
      - lynx
      - fdutils
      - linux-tools-generic
      - build-essential
      - libssl-dev
      - python-dev
      - python3-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran
      - pkg-config
      - zlib1g-dev
      - libpng-dev
      - libfreetype6-dev
      - libxml2-dev
      - libffi-dev
    state: present

# create Downloads folder in ansible_user home if one not already present.
- name: make sure there is a Downloads folder in ansible_user
  file:
    path: ~/Downloads
    state: directory