---
# This playbook deploys the whole research application stack.

- name: set up new servers
  hosts: new_servers

  roles:
    - new_server

- name: apply common configuration to all nodes
  hosts: all

  roles:
    - common

- name: configure and deploy the PostgreSQL database
  hosts: postgres_servers

  roles:
    - postgresql

- name: deploy jupyterhub server
  hosts: jupyterhub_servers

  roles:
    - jupyterhub

- name: deploy R
  hosts: r_servers

  roles:
    - r

- name: deploy RStudio server
  hosts: jupyterhub_servers

  roles:
    - rstudio

- name: deploy sourcenet application
  hosts: sourcenet_servers

  roles:
    - sourcenet
