# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0003_auto_20150915_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_author',
            name='match_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article_subject',
            name='match_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
