# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0004_auto_20160108_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_author',
            name='more_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article_author',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
