# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet', '0005_auto_20160120_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_author',
            name='more_organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article_subject',
            name='more_organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article_subject',
            name='organization_string',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
