# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 22:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sourcenet', '0007_auto_20160210_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_names_coder10_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder10_article_data_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder10_detected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder10_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder10_source_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_names_coder4_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder4_article_data_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder4_detected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder4_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder4_source_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_names_coder5_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder5_article_data_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder5_detected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder5_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder5_source_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_names_coder6_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder6_article_data_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder6_detected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder6_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder6_source_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_names_coder7_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder7_article_data_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder7_detected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder7_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder7_source_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_names_coder8_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder8_article_data_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder8_detected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder8_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder8_source_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_names_coder9_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder9_article_data_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder9_detected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder9_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder9_source_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_ties_coder10_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder10_id_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder10_mention_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_ties_coder4_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder4_id_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder4_mention_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_ties_coder5_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder5_id_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder5_mention_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_ties_coder6_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder6_id_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder6_mention_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_ties_coder7_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder7_id_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder7_mention_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_ties_coder8_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder8_id_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder8_mention_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_ties_coder9_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder9_id_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_ties',
            name='coder9_mention_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
