# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0008_auto_20160222_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis_reliability_names',
            old_name='coder10_source_type',
            new_name='coder10_person_type',
        ),
        migrations.RenameField(
            model_name='analysis_reliability_names',
            old_name='coder1_source_type',
            new_name='coder1_person_type',
        ),
        migrations.RenameField(
            model_name='analysis_reliability_names',
            old_name='coder2_source_type',
            new_name='coder2_person_type',
        ),
        migrations.RenameField(
            model_name='analysis_reliability_names',
            old_name='coder3_source_type',
            new_name='coder3_person_type',
        ),
        migrations.RenameField(
            model_name='analysis_reliability_names',
            old_name='coder4_source_type',
            new_name='coder4_person_type',
        ),
        migrations.RenameField(
            model_name='analysis_reliability_names',
            old_name='coder5_source_type',
            new_name='coder5_person_type',
        ),
        migrations.RenameField(
            model_name='analysis_reliability_names',
            old_name='coder6_source_type',
            new_name='coder6_person_type',
        ),
        migrations.RenameField(
            model_name='analysis_reliability_names',
            old_name='coder7_source_type',
            new_name='coder7_person_type',
        ),
        migrations.RenameField(
            model_name='analysis_reliability_names',
            old_name='coder8_source_type',
            new_name='coder8_person_type',
        ),
        migrations.RenameField(
            model_name='analysis_reliability_names',
            old_name='coder9_source_type',
            new_name='coder9_person_type',
        ),
    ]
