# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0009_auto_20160223_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder10_article_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder10_coder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder1_article_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder1_coder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder2_article_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder2_coder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder3_article_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder3_coder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder4_article_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder4_coder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder5_article_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder5_coder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder6_article_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder6_coder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder7_article_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder7_coder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder8_article_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder8_coder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder9_article_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder9_coder_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
