# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0010_auto_20160224_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder10_person_type_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder1_person_type_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder2_person_type_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder3_person_type_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder4_person_type_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder5_person_type_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder6_person_type_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder7_person_type_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder8_person_type_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis_reliability_names',
            name='coder9_person_type_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
