# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0011_auto_20160224_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis_reliability_names',
            name='article',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_names',
            name='coder1',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_names',
            name='coder10',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_names',
            name='coder2',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_names',
            name='coder3',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_names',
            name='coder4',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_names',
            name='coder5',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_names',
            name='coder6',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_names',
            name='coder7',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_names',
            name='coder8',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_names',
            name='coder9',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_names',
            name='person',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_ties',
            name='coder1',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_ties',
            name='coder10',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_ties',
            name='coder2',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_ties',
            name='coder3',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_ties',
            name='coder4',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_ties',
            name='coder5',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_ties',
            name='coder6',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_ties',
            name='coder7',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_ties',
            name='coder8',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_ties',
            name='coder9',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_ties',
            name='person',
        ),
        migrations.RemoveField(
            model_name='analysis_reliability_ties',
            name='relation_person',
        ),
        migrations.DeleteModel(
            name='Analysis_Reliability_Names',
        ),
        migrations.DeleteModel(
            name='Analysis_Reliability_Ties',
        ),
    ]
