# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0012_auto_20160225_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='cleanup_status',
            field=models.CharField(blank=True, default='new', max_length=255, null=True),
        ),
    ]
