# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet', '0013_auto_20160406_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_author',
            name='lookup_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article_author',
            name='verbatim_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article_subject',
            name='lookup_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article_subject',
            name='verbatim_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='cleanup_status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('author_fixed', 'author fixed'), ('author_error', 'author error'), ('text_fixed', 'text fixed'), ('text_error', 'text error'), ('author_and_text_fixed', 'author & text fixed'), ('complete', 'complete'), ('error', 'error')], default='new', max_length=255, null=True),
        ),
    ]
