# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0015_auto_20160608_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternate_author_match',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alternate_author_match',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='alternate_subject_match',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alternate_subject_match',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
