# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0016_auto_20160817_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_organization',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_organization',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
