# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet', '0017_auto_20160924_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_data',
            name='projects',
            field=models.ManyToManyField(blank=True, to='sourcenet.Project'),
        ),
    ]
