# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 05:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcenet', '0018_auto_20160924_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternate_name',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcenet.Organization'),
        ),
        migrations.AlterField(
            model_name='article',
            name='newspaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcenet.Newspaper'),
        ),
        migrations.AlterField(
            model_name='article_author',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcenet.Organization'),
        ),
        migrations.AlterField(
            model_name='article_author',
            name='original_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcenet_article_author_original_person_set', to='sourcenet.Person'),
        ),
        migrations.AlterField(
            model_name='article_subject',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcenet.Document'),
        ),
        migrations.AlterField(
            model_name='article_subject',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcenet.Organization'),
        ),
        migrations.AlterField(
            model_name='article_subject',
            name='original_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcenet_article_subject_original_person_set', to='sourcenet.Person'),
        ),
        migrations.AlterField(
            model_name='articles_to_migrate',
            name='coder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articles_to_migrate',
            name='newspaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcenet.Newspaper'),
        ),
        migrations.AlterField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcenet.Organization'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcenet.Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcenet.Location'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sourcenet.Organization'),
        ),
    ]
