# Generated by Django 2.0.8 on 2018-08-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0019_auto_20171216_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_text',
            name='do_clean_on_save',
            field=models.BooleanField(default=True),
        ),
    ]
