# Generated by Django 2.0.8 on 2018-08-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0020_article_text_do_clean_on_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
