# Generated by Django 2.1.5 on 2019-01-30 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
        ('sourcenet', '0021_article_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_data',
            name='work_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Work_Log'),
        ),
    ]
