# Generated by Django 2.2 on 2019-04-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0022_article_data_work_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person_external_uuid',
            options={'ordering': ['id_type', 'source', 'name', 'uuid']},
        ),
        migrations.AddField(
            model_name='person_external_uuid',
            name='id_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
