# Generated by Django 2.2.1 on 2019-05-04 21:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0025_auto_20190504_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_data_notes',
            name='content_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article_data_notes',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
