# Generated by Django 2.2.6 on 2019-10-12 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0024_auto_20190906_1918'),
        ('context_text', '0027_auto_20190508_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Entity'),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Entity'),
        ),
        migrations.AddField(
            model_name='organization',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Entity'),
        ),
        migrations.AddField(
            model_name='person',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Entity'),
        ),
    ]
