# Generated by Django 2.2.6 on 2019-10-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0029_auto_20191015_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='unique_identifier_type',
            field=models.CharField(blank=True, choices=[('permalink', 'permalink'), ('article_newsbank_id', 'article_newsbank_id')], default='permalink', max_length=255, null=True),
        ),
    ]
