# Generated by Django 2.2.6 on 2019-10-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0030_article_unique_identifier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unique_identifier_type',
            field=models.CharField(blank=True, choices=[('permalink', 'permalink'), ('article_newsbank_id', 'article_newsbank_id')], default=None, max_length=255, null=True),
        ),
    ]
