# Generated by Django 3.1.2 on 2020-12-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0032_auto_20191205_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternate_name',
            name='details_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='details_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article_author',
            name='details_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article_data_notes',
            name='content_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article_notes',
            name='content_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article_subject',
            name='details_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='details_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='details_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='details_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
