# Generated by Django 3.1.4 on 2021-05-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0033_auto_20201218_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_data_notes',
            name='content_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article_data_notes',
            name='content_json_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article_notes',
            name='content_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article_notes',
            name='content_json_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article_rawdata',
            name='content_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article_text',
            name='content_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
