# Generated by Django 4.0.4 on 2022-05-26 03:10

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('context_text', '0034_auto_20210507_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_author',
            name='original_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_original_person_set', to='context_text.person'),
        ),
        migrations.AlterField(
            model_name='article_subject',
            name='original_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_original_person_set', to='context_text.person'),
        ),
        migrations.CreateModel(
            name='NetworkDataOutputLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_spec_json', models.JSONField()),
                ('data_spec_json_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('network_data', models.TextField()),
                ('network_data_content_type', models.CharField(blank=True, choices=[('canonical', 'Canonical'), ('text', 'Text'), ('html', 'HTML'), ('json', 'JSON'), ('xml', 'XML'), ('other', 'Other'), ('none', 'None')], default='text', max_length=255, null=True)),
                ('network_data_format', models.CharField(blank=True, choices=[('simple_matrix', 'Simple Matrix'), ('csv_matrix', 'CSV Matrix'), ('tab_delimited_matrix', 'Tab-Delimited Matrix')], max_length=255, null=True)),
                ('network_data_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('request_type', models.CharField(blank=True, choices=[('json', 'JSON'), ('http_request', 'HTTP request')], default='json', max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['last_modified', 'create_date'],
            },
        ),
    ]
