# Generated by Django 4.0.4 on 2022-06-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_text', '0036_networkdataoutputlog_network_data_file_path_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['pub_date'], name='context_tex_pub_dat_9d827f_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['unique_identifier'], name='context_tex_unique__554c64_idx'),
        ),
        migrations.AddIndex(
            model_name='article_author',
            index=models.Index(fields=['verbatim_name'], name='context_tex_verbati_e6f422_idx'),
        ),
        migrations.AddIndex(
            model_name='article_data',
            index=models.Index(fields=['coder_type'], name='context_tex_coder_t_2ec6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='article_subject',
            index=models.Index(fields=['verbatim_name'], name='context_tex_verbati_dffbbf_idx'),
        ),
    ]
