---
# These tasks install and configure apache2 and mod_wsgi for python 3.

# Install apache2 and mod_wsgi for Python 3
- name: Install OS packages for apache2 and mod_wsgi for Python 3
  become: yes
  become_user: root
  apt:
    name:
      - apache2
      - libapache2-mod-wsgi-py3

# Enable mod_wsgi
- name: Enable mod_wsgi module.
  become: yes
  become_user: root
  apache2_module:
    state: present
    name: wsgi

# restart apache
- name: restart apache2
  become: yes
  become_user: root
  service:
    name: apache2
    state: restarted

# open firewall for http and https  
- name: Allow HTTP ports
  become: yes
  become_user: root
  ufw:
    rule: allow
    port: http

- name: Allow HTTPS port
  become: yes
  become_user: root
  ufw:
    rule: allow
    port: https
