---
# This playbook will install CRAN R apt repository, then install R.

# Add apt source for CRAN R.
- name: Create APT source for CRAN R.
  become: yes
  become_user: root
  template:
    src: CRAN-R.list.j2
    dest: /etc/apt/sources.list.d

# Add apt key for CRAN R source
- name: Add an apt key by id from a keyserver
  become: yes
  become_user: root
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E084DAB9

# update apt cache
- name: Update apt cache
  become: yes
  become_user: root
  apt:
    update_cache: yes

# install R base
- name: install r-base
  become: yes
  become_user: root
  apt:
    name: r-base
    state: present
