---
# This playbook contains common plays that will be run on all nodes.

# Install first set of needed packages
- name: install lots of packages
  become: yes
  become_user: root
  apt:
    name:
      - screen
      - vim
      - git
      - linux-image-generic
      - linux-headers-generic
      - python
      - python3
      - subversion
      - links
      - lynx
      - fdutils
      - linux-tools-generic
      - build-essential
      - libssl-dev
      - python-dev
      - python3-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran
      - pkg-config
      - zlib1g-dev
      - libpng-dev
      - libfreetype6-dev
      - libxml2-dev
      - libffi-dev
      - libxml2
      - libxslt1-dev
      - libyaml-dev
      - curl
    state: present

# ==> pip

# download install script
- name: Download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: ~/Downloads/get-pip.py

# install pip in python 2
- name: Install pip in python 2
  become: yes
  become_user: root
  shell: python get-pip.py
  args:
    chdir: ~/Downloads

# install pip in python 3
- name: Install pip in python 3
  become: yes
  become_user: root
  shell: python3 get-pip.py
  args:
    chdir: ~/Downloads

# ==> virtualenv and virtualenvwrapper
#- name: install virtualenv and virtualenvwrapper
#  become: yes
#  become_user: root
#  pip:
#    executable: pip3
