UPDATE django_content_type SET app_label='context_text' WHERE app_label='sourcenet';
UPDATE django_migrations SET app='context_text' WHERE app='sourcenet';

/*
-- Get the index names of all the indexes for tables in this application.
--     (and get each twice for ease of making ALTER INDEX statements)
SELECT indexname, indexname
FROM pg_indexes
WHERE tablename LIKE 'sourcenet_%';
*/

ALTER INDEX sourcenet_alternate_author_match_pkey RENAME TO context_text_alternate_author_match_pkey;
ALTER INDEX sourcenet_alternate_name_pkey RENAME TO context_text_alternate_name_pkey;
ALTER INDEX sourcenet_alternate_source_match_pkey RENAME TO context_text_alternate_source_match_pkey;
ALTER INDEX sourcenet_article_author_id_pkey RENAME TO context_text_article_author_id_pkey;
ALTER INDEX sourcenet_article_data_id_pkey RENAME TO context_text_article_data_id_pkey;
ALTER INDEX sourcenet_article_data_locations_id_pkey RENAME TO context_text_article_data_locations_id_pkey;
ALTER INDEX sourcenet_article_data_notes_pkey RENAME TO context_text_article_data_notes_pkey;
ALTER INDEX sourcenet_article_data_projects_article_data_id_project_id_key RENAME TO context_text_article_data_projects_article_data_id_project_id_key;
ALTER INDEX sourcenet_article_data_projects_pkey RENAME TO context_text_article_data_projects_pkey;
ALTER INDEX sourcenet_article_data_topics_id_pkey RENAME TO context_text_article_data_topics_id_pkey;
ALTER INDEX sourcenet_article_id_pkey RENAME TO context_text_article_id_pkey;
ALTER INDEX sourcenet_article_notes_id_pkey RENAME TO context_text_article_notes_id_pkey;
ALTER INDEX sourcenet_article_rawdata_id_pkey RENAME TO context_text_article_rawdata_id_pkey;
ALTER INDEX sourcenet_article_subject_mention_pkey RENAME TO context_text_article_subject_mention_pkey;
ALTER INDEX sourcenet_article_subject_pkey RENAME TO context_text_article_subject_pkey;
ALTER INDEX sourcenet_article_subject_quotation_pkey RENAME TO context_text_article_subject_quotation_pkey;
ALTER INDEX sourcenet_article_subject_topic_article_subject_id_topic_id_key RENAME TO context_text_article_subject_topic_article_subject_id_topic_id_key;
ALTER INDEX sourcenet_article_subject_topics_pkey RENAME TO context_text_article_subject_topics_pkey;
ALTER INDEX sourcenet_article_text_id_pkey RENAME TO context_text_article_text_id_pkey;
ALTER INDEX sourcenet_articles_to_migrate_pkey RENAME TO context_text_articles_to_migrate_pkey;
ALTER INDEX sourcenet_document_id_pkey RENAME TO context_text_document_id_pkey;
ALTER INDEX sourcenet_import_error_id_pkey RENAME TO context_text_import_error_id_pkey;
ALTER INDEX sourcenet_location_id_pkey RENAME TO context_text_location_id_pkey;
ALTER INDEX sourcenet_newspaper_id_pkey RENAME TO context_text_newspaper_id_pkey;
ALTER INDEX sourcenet_organization_id_pkey RENAME TO context_text_organization_id_pkey;
ALTER INDEX sourcenet_person_external_uuid_pkey RENAME TO context_text_person_external_uuid_pkey;
ALTER INDEX sourcenet_person_id_pkey RENAME TO context_text_person_id_pkey;
ALTER INDEX sourcenet_person_newspaper_pkey RENAME TO context_text_person_newspaper_pkey;
ALTER INDEX sourcenet_person_organization_id_pkey RENAME TO context_text_person_organization_id_pkey;
ALTER INDEX sourcenet_project_pkey RENAME TO context_text_project_pkey;
ALTER INDEX sourcenet_subject_organization_pkey RENAME TO context_text_subject_organization_pkey;
ALTER INDEX sourcenet_temp_section_id_pkey RENAME TO context_text_temp_section_id_pkey;
ALTER INDEX sourcenet_topic_id_pkey RENAME TO context_text_topic_id_pkey;
ALTER INDEX sourcenet_alternate_author_match_a8452ca7 RENAME TO context_text_alternate_author_match_a8452ca7;
ALTER INDEX sourcenet_alternate_author_match_dcfa415f RENAME TO context_text_alternate_author_match_dcfa415f;
ALTER INDEX sourcenet_alternate_name_26b2345e RENAME TO context_text_alternate_name_26b2345e;
ALTER INDEX sourcenet_alternate_name_a8452ca7 RENAME TO context_text_alternate_name_a8452ca7;
ALTER INDEX sourcenet_alternate_source_match_a8452ca7 RENAME TO context_text_alternate_source_match_a8452ca7;
ALTER INDEX sourcenet_alternate_subject_match_f7850ab4 RENAME TO context_text_alternate_subject_match_f7850ab4;
ALTER INDEX sourcenet_article_author_04bb648d RENAME TO context_text_article_author_04bb648d;
ALTER INDEX sourcenet_article_author_26b2345e RENAME TO context_text_article_author_26b2345e;
ALTER INDEX sourcenet_article_author_article_data_id RENAME TO context_text_article_author_article_data_id;
ALTER INDEX sourcenet_article_author_person_id RENAME TO context_text_article_author_person_id;
ALTER INDEX sourcenet_article_author_varchar RENAME TO context_text_article_author_varchar;
ALTER INDEX sourcenet_article_data_article_id RENAME TO context_text_article_data_article_id;
ALTER INDEX sourcenet_article_data_coder_id RENAME TO context_text_article_data_coder_id;
ALTER INDEX sourcenet_article_data_locations_article_data_id RENAME TO context_text_article_data_locations_article_data_id;
ALTER INDEX sourcenet_article_data_locations_article_data_id_location_id RENAME TO context_text_article_data_locations_article_data_id_location_id;
ALTER INDEX sourcenet_article_data_locations_location_id RENAME TO context_text_article_data_locations_location_id;
ALTER INDEX sourcenet_article_data_notes_34ebb85f RENAME TO context_text_article_data_notes_34ebb85f;
ALTER INDEX sourcenet_article_data_projects_34ebb85f RENAME TO context_text_article_data_projects_34ebb85f;
ALTER INDEX sourcenet_article_data_projects_b098ad43 RENAME TO context_text_article_data_projects_b098ad43;
ALTER INDEX sourcenet_article_data_topics_article_data_id RENAME TO context_text_article_data_topics_article_data_id;
ALTER INDEX sourcenet_article_data_topics_article_data_id_topic_id RENAME TO context_text_article_data_topics_article_data_id_topic_id;
ALTER INDEX sourcenet_article_data_topics_topic_id RENAME TO context_text_article_data_topics_topic_id;
ALTER INDEX sourcenet_article_id RENAME TO context_text_article_id;
ALTER INDEX sourcenet_article_newspaper_id RENAME TO context_text_article_newspaper_id;
ALTER INDEX sourcenet_article_notes_article_id RENAME TO context_text_article_notes_article_id;
ALTER INDEX sourcenet_article_pub_date RENAME TO context_text_article_pub_date;
ALTER INDEX sourcenet_article_rawdata_article_id RENAME TO context_text_article_rawdata_article_id;
ALTER INDEX sourcenet_article_section RENAME TO context_text_article_section;
ALTER INDEX sourcenet_article_subject_04bb648d RENAME TO context_text_article_subject_04bb648d;
ALTER INDEX sourcenet_article_subject_26b2345e RENAME TO context_text_article_subject_26b2345e;
ALTER INDEX sourcenet_article_subject_34ebb85f RENAME TO context_text_article_subject_34ebb85f;
ALTER INDEX sourcenet_article_subject_a8452ca7 RENAME TO context_text_article_subject_a8452ca7;
ALTER INDEX sourcenet_article_subject_e7fafc10 RENAME TO context_text_article_subject_e7fafc10;
ALTER INDEX sourcenet_article_subject_mention_f7850ab4 RENAME TO context_text_article_subject_mention_f7850ab4;
ALTER INDEX sourcenet_article_subject_quotation_f7850ab4 RENAME TO context_text_article_subject_quotation_f7850ab4;
ALTER INDEX sourcenet_article_subject_topics_19b4d727 RENAME TO context_text_article_subject_topics_19b4d727;
ALTER INDEX sourcenet_article_subject_topics_f7850ab4 RENAME TO context_text_article_subject_topics_f7850ab4;
ALTER INDEX sourcenet_article_text_article_id RENAME TO context_text_article_text_article_id;
ALTER INDEX sourcenet_articles_to_migrate_article_id RENAME TO context_text_articles_to_migrate_article_id;
ALTER INDEX sourcenet_articles_to_migrate_coder_id RENAME TO context_text_articles_to_migrate_coder_id;
ALTER INDEX sourcenet_articles_to_migrate_newspaper_id RENAME TO context_text_articles_to_migrate_newspaper_id;
ALTER INDEX sourcenet_document_organization_id RENAME TO context_text_document_organization_id;
ALTER INDEX sourcenet_newspaper_organization_id RENAME TO context_text_newspaper_organization_id;
ALTER INDEX sourcenet_organization_location_id RENAME TO context_text_organization_location_id;
ALTER INDEX sourcenet_person_26b2345e RENAME TO context_text_person_26b2345e;
ALTER INDEX sourcenet_person_external_uuid_a8452ca7 RENAME TO context_text_person_external_uuid_a8452ca7;
ALTER INDEX sourcenet_person_newspaper_a8452ca7 RENAME TO context_text_person_newspaper_a8452ca7;
ALTER INDEX sourcenet_person_newspaper_f0d9b265 RENAME TO context_text_person_newspaper_f0d9b265;
ALTER INDEX sourcenet_person_organization_organization_id RENAME TO context_text_person_organization_organization_id;
ALTER INDEX sourcenet_person_organization_person_id RENAME TO context_text_person_organization_person_id;
ALTER INDEX sourcenet_subject_organization_26b2345e RENAME TO context_text_subject_organization_26b2345e;
ALTER INDEX sourcenet_subject_organization_f7850ab4 RENAME TO context_text_subject_organization_f7850ab4;
ALTER INDEX sourcenet_article_data_work_log_id_e805250b RENAME TO context_text_article_data_work_log_id_e805250b;

/*
-- Get the table names of all the tables for this application.
--     (and get each twice for ease of making ALTER TABLE statements)
SELECT table_name, table_name
FROM information_schema.tables
WHERE table_name LIKE 'sourcenet_%'
    AND table_type='BASE TABLE';
*/

ALTER TABLE sourcenet_person_organization RENAME TO context_text_person_organization;
ALTER TABLE sourcenet_person_newspaper RENAME TO context_text_person_newspaper;
ALTER TABLE sourcenet_person_external_uuid RENAME TO context_text_person_external_uuid;
ALTER TABLE sourcenet_person RENAME TO context_text_person;
ALTER TABLE sourcenet_newspaper RENAME TO context_text_newspaper;
ALTER TABLE sourcenet_article_data RENAME TO context_text_article_data;
ALTER TABLE sourcenet_article_subject_mention RENAME TO context_text_article_subject_mention;
ALTER TABLE sourcenet_article RENAME TO context_text_article;
ALTER TABLE sourcenet_article_subject RENAME TO context_text_article_subject;
ALTER TABLE sourcenet_subject_organization RENAME TO context_text_subject_organization;
ALTER TABLE sourcenet_organization RENAME TO context_text_organization;
ALTER TABLE sourcenet_location RENAME TO context_text_location;
ALTER TABLE sourcenet_import_error RENAME TO context_text_import_error;
ALTER TABLE sourcenet_document RENAME TO context_text_document;
ALTER TABLE sourcenet_article_subject_topics RENAME TO context_text_article_subject_topics;
ALTER TABLE sourcenet_article_subject_quotation RENAME TO context_text_article_subject_quotation;
ALTER TABLE sourcenet_topic RENAME TO context_text_topic;
ALTER TABLE sourcenet_article_data_topics RENAME TO context_text_article_data_topics;
ALTER TABLE sourcenet_article_data_projects RENAME TO context_text_article_data_projects;
ALTER TABLE sourcenet_article_data_locations RENAME TO context_text_article_data_locations;
ALTER TABLE sourcenet_article_author RENAME TO context_text_article_author;
ALTER TABLE sourcenet_temp_section RENAME TO context_text_temp_section;
ALTER TABLE sourcenet_project RENAME TO context_text_project;
ALTER TABLE sourcenet_articles_to_migrate RENAME TO context_text_articles_to_migrate;
ALTER TABLE sourcenet_article_rawdata RENAME TO context_text_article_rawdata;
ALTER TABLE sourcenet_article_notes RENAME TO context_text_article_notes;
ALTER TABLE sourcenet_article_data_notes RENAME TO context_text_article_data_notes;
ALTER TABLE sourcenet_article_text RENAME TO context_text_article_text;
ALTER TABLE sourcenet_alternate_subject_match RENAME TO context_text_alternate_subject_match;
ALTER TABLE sourcenet_alternate_name RENAME TO context_text_alternate_name;
ALTER TABLE sourcenet_alternate_author_match RENAME TO context_text_alternate_author_match;

/*
-- Get the sequence names of all the sequences for this application.
--     (and get each twice for ease of making ALTER SEQUENCE statements)
SELECT sequence_name, sequence_name
FROM information_schema.sequences
WHERE sequence_name LIKE 'sourcenet_%';
*/

ALTER SEQUENCE sourcenet_topic_id_seq RENAME TO context_text_topic_id_seq;
ALTER SEQUENCE sourcenet_person_organization_id_seq RENAME TO context_text_person_organization_id_seq;
ALTER SEQUENCE sourcenet_person_newspaper_id_seq RENAME TO context_text_person_newspaper_id_seq;
ALTER SEQUENCE sourcenet_person_external_uuid_id_seq RENAME TO context_text_person_external_uuid_id_seq;
ALTER SEQUENCE sourcenet_location_id_seq RENAME TO context_text_location_id_seq;
ALTER SEQUENCE sourcenet_import_error_id_seq RENAME TO context_text_import_error_id_seq;
ALTER SEQUENCE sourcenet_article_subject_topics_id_seq RENAME TO context_text_article_subject_topics_id_seq;
ALTER SEQUENCE sourcenet_article_subject_quotation_id_seq RENAME TO context_text_article_subject_quotation_id_seq;
ALTER SEQUENCE sourcenet_article_subject_mention_id_seq RENAME TO context_text_article_subject_mention_id_seq;
ALTER SEQUENCE sourcenet_article_subject_id_seq RENAME TO context_text_article_subject_id_seq;
ALTER SEQUENCE sourcenet_temp_section_id_seq RENAME TO context_text_temp_section_id_seq;
ALTER SEQUENCE sourcenet_subject_organization_id_seq RENAME TO context_text_subject_organization_id_seq;
ALTER SEQUENCE sourcenet_source_organization_id_seq RENAME TO context_text_source_organization_id_seq;
ALTER SEQUENCE sourcenet_project_id_seq RENAME TO context_text_project_id_seq;
ALTER SEQUENCE sourcenet_document_id_seq RENAME TO context_text_document_id_seq;
ALTER SEQUENCE sourcenet_articles_to_migrate_id_seq RENAME TO context_text_articles_to_migrate_id_seq;
ALTER SEQUENCE sourcenet_article_source_topics_id_seq RENAME TO context_text_article_source_topics_id_seq;
ALTER SEQUENCE sourcenet_article_source_id_seq RENAME TO context_text_article_source_id_seq;
ALTER SEQUENCE sourcenet_article_rawdata_id_seq RENAME TO context_text_article_rawdata_id_seq;
ALTER SEQUENCE sourcenet_article_notes_id_seq RENAME TO context_text_article_notes_id_seq;
ALTER SEQUENCE sourcenet_article_data_topics_id_seq RENAME TO context_text_article_data_topics_id_seq;
ALTER SEQUENCE sourcenet_article_data_projects_id_seq RENAME TO context_text_article_data_projects_id_seq;
ALTER SEQUENCE sourcenet_article_data_notes_id_seq RENAME TO context_text_article_data_notes_id_seq;
ALTER SEQUENCE sourcenet_person_id_seq RENAME TO context_text_person_id_seq;
ALTER SEQUENCE sourcenet_organization_id_seq RENAME TO context_text_organization_id_seq;
ALTER SEQUENCE sourcenet_newspaper_id_seq RENAME TO context_text_newspaper_id_seq;
ALTER SEQUENCE sourcenet_article_text_id_seq RENAME TO context_text_article_text_id_seq;
ALTER SEQUENCE sourcenet_article_data_locations_id_seq RENAME TO context_text_article_data_locations_id_seq;
ALTER SEQUENCE sourcenet_article_data_id_seq RENAME TO context_text_article_data_id_seq;
ALTER SEQUENCE sourcenet_article_author_id_seq RENAME TO context_text_article_author_id_seq;
ALTER SEQUENCE sourcenet_article_id_seq RENAME TO context_text_article_id_seq;
ALTER SEQUENCE sourcenet_alternate_source_match_id_seq RENAME TO context_text_alternate_source_match_id_seq;
ALTER SEQUENCE sourcenet_alternate_name_id_seq RENAME TO context_text_alternate_name_id_seq;
ALTER SEQUENCE sourcenet_alternate_author_match_id_seq RENAME TO context_text_alternate_author_match_id_seq;
