---
# This playbook will install and configure postgresql.

# Install PostgreSQL
- name: Install Postgresql packages
  become: yes
  become_user: root
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - postgresql-server-dev-10

# open firewall for postgresql
- name: Allow postgresql ports
  become: yes
  become_user: root
  ufw:
    rule: allow
    port: postgresql

#- name: Create Mysql configuration file
#  template: src=my.cnf.j2 dest=/etc/my.cnf
#  notify:
#  - restart mysql
#
#- name: Start Mysql Service
#  service: name=mysqld state=started enabled=yes
#
#- name: insert iptables rule
#  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
#              insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
#  notify: restart iptables
#
#- name: Create Application Database
#  mysql_db: name={{ dbname }} state=present
#
#- name: Create Application DB User
#  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
